[package]
name = "aichat-scope-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
dialoguer = "0.11.0"
anyhow = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
heck = "0.4"
