[package]
name = "acl-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
casbin = { path = "../vendor/casbin-rs" }
anyhow = "1.0"
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }